{ pkgs, systemSettings, lib, config, home-manager, ... }:
{
  programs.niri.enable = true;

  environment.systemPackages = with pkgs; [
     niri
     wofi
     wofi-emoji
     pywal
     waybar
     cava
     hyprlock
     # hyprpaper
     brightnessctl
  ];

  # xdg.configFile."niri/config.kdl".text = ''
  # // Niri Configuration for ${systemSettings.hostname}
  # // Generated by NixOS configuration
  # '';
}
