#History Files
#Tue Apr 28 16:56:05 AEST 2026
history.0=file\:/run/media/jeremiah/Expansion/Documents/Tabs/Do%20smth%20w%20this.tg
history.1=file\:/run/media/jeremiah/Expansion/Documents/Tabs/OG%201.tg
history.2=file\:/home/jeremiah/Documents/TABs/Me/Tim's%20Fishman%20Demo%20Riffs/Overwound%20Humbucker%20Riff.tg
history.3=file\:/home/jeremiah/Documents/TABs/Me/These%20Colours%20Don't%20Run.tg
history.4=file\:/home/jeremiah/Documents/TABs/Me/Tim's%20Fishman%20Demo%20Riffs/Playing%20God%20Interlude%20-%20Neck%20&%20Bridge%20Single%20Coil.tg
history.5=file\:/home/jeremiah/Documents/TABs/Me/Butter.tg
history.6=file\:/home/jeremiah/Documents/TABs/Me/Tim's%20Fishman%20Demo%20Riffs/Bridge%20Pickup%20-%20Voice%202.tg
history.7=file\:/home/jeremiah/Documents/TABs/Me/Sunshine%20Of%20Your%20Love.tg
history.8=file\:/home/jeremiah/Documents/TABs/Me/River%20Flows%20In%20You.tg
history.9=file\:/home/jeremiah/Documents/TABs/Me/When%20Doves%20Cry%20Synth.tg
history.count=10
history.path=/run/media/jeremiah/Expansion/Documents/Tabs
